# ~/mozaik-demo/config.yml

host: localhost # Mozaïk host
port: 5000      # Mozaïk port

# Mozaïk dashboard rotation interval (ms)
rotationDuration: 8000

dashboards:
    # first dashboard
    - columns: 4
      rows:    3
      widgets: []

    # second dashboard
    - columns: 3
      rows:    3
      widgets: []
